image: haskell:latest

before_script:
  - apt-get update && apt-get install xz-utils make
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
  - stack build

build:
  cache:
    paths:
      - _cache
      - .stack
      - public
  script:
    - stack exec site build
  except:
    - master

pages:
  cache:
    paths:
      - _cache
      - .stack
      - public
  script:
    - stack exec site build
  artifacts:
    paths:
      - public
  only:
    - master
