name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            _cache
            public
            .stack
            .stack-work
          key: ${{ runner.os }}-${{ hashFiles('./stack.yaml.lock') }}

      - name: Prepare Haskell environment
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.3'
          stack-version: 'latest'

      - name: Build the executable file
        run: |
          stack --version
          stack setup
          stack install --only-dependencies
          stack build
      
      - name: Build the site
        run: stack exec site build || stack exec site rebuild

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          cname: scp-079.org
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
